apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: multi-cluster-germans-dev-tls
spec:
  secretName: multi-cluster-germans-dev
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-cluster.germans.dev
  dnsNames:
    - multi-cluster.germans.dev
